name: access-token

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  issues: write
  packages: read
  pull-requests: write
  repository-projects: write
  statuses: write

jobs:
  get-token:
    uses: thejaswicy/autobots-demo/.github/workflows/access-token.yml@main
    secrets: inherit
